# Generated by Django 2.2.3 on 2019-08-30 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='posting',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='posting',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
